version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    groups:
      # Group all dependencies together
      dependencies:
        patterns:
          - "*"
      # Group all dev dependencies together
      dev-dependencies:
        patterns:
          - "*"
        dependency-type: "development"
    commit-message:
      prefix: "npm"
      include: "scope"
    reviewers:
      - "fabiorodriguesdev"
    assignees:
      - "fabiorodriguesdev"
      